version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234        # root 사용자 비밀번호
      MYSQL_USER: user                 # 새로 생성할 일반 사용자
      MYSQL_PASSWORD: 1234             # 일반 사용자의 비밀번호
      MYSQL_DATABASE: LifeMaster_db    # 생성할 데이터베이스
    ports:
      - "3307:3306"                    # 호스트 3307 -> 컨테이너 3306
    volumes:
      - mysql_data:/var/lib/mysql      # 데이터 영속성 볼륨

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/LifeMaster_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  mysql_data:
